backend/controllers/TransaksibarangController.php
<?php

namespace backend\controllers;

use Yii;
use yii\helpers\ArrayHelper;
use backend\models\SatuanbrgM;
use backend\models\BarangM;
use backend\models\JualbarangT;
use backend\models\JualbarangdetT;
use backend\models\PelangganM;
use backend\models\TandabayarR;
use backend\models\JenisbrgM;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

class TransaksibarangController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','tambahbarang'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $modBarang = new BarangM();
        $model = new JualbarangT();
        $modJualBrngDet = new JualbarangdetT();

        if(Yii::$app->request->post()) {
            $totalPenjualan = 0;
            $connection = \Yii::$app->db;
            $transaction = $connection->beginTransaction();
            try {
                $model->load(Yii::$app->request->post());
                $model->tgl_jual = Yii::$app->formatter->asDate($model->tgl_jual,'php:Y-m-d');
                if(!empty($model->tgl_ambil))
                    $model->tgl_ambil = Yii::$app->formatter->asDate($model->tgl_ambil,'php:Y-m-d');
                if(!empty($model->tgl_penagihan))
                    $model->tgl_penagihan = Yii::$app->formatter->asDate($model->tgl_penagihan,'php:Y-m-d');
                if (isset(Yii::$app->request->post()['JualbarangdetT'])) {
                    foreach (Yii::$app->request->post()['JualbarangdetT'] AS $i => $data) {
                        $totalPenjualan += $data['jumlah'];
                    }
                }
                $model->total = $totalPenjualan;
                if(empty($model->panjer))
                    $model->panjer = 0;
                if(empty($model->diskon))
                    $model->diskon = 0;
                if(empty($model->sisa))
                    $model->sisa = 0;
                if(empty($model->tgl_penagihan))
                    $model->tgl_penagihan = date('Y-m-d',strtotime('+7 days'));
                if($model->validate()){
                    $model->save();
                    foreach (Yii::$app->request->post()['JualbarangdetT'] AS $i => $data) {
                        $modJualBrngDet = new JualbarangdetT();
                        $modJualBrngDet->attributes = $data;
                        $modJualBrngDet->jualbarang_id = $model->jualbarang_id;
                        if($modJualBrngDet->validate())
                            $modJualBrngDet->save();
                    }
                    $transaction->commit();
                    Yii::$app->getSession()->setFlash('success', 'Sukses Menambahkan Transaksi !');
                    return $this->redirect(['index', 'id' => $model->jualbarang_id]);
                }
            }catch(\Exception $e) {
                $transaction->rollBack();
                throw $e;
            }
        }

        return $this->render('index',[
            'modBarang'=>$modBarang,
            'model'=>$model,
            'modJualBrngDet'=>$modJualBrngDet
        ]);
    }

    public function actionTambahbarang()
    {
        if(Yii::$app->request->isAjax) {
            $modJualBarangDet = new JualbarangdetT();
            $barang_id = $_POST['barang_id'];
            $urutan = $_POST['urutan'];
            if (!empty($barang_id) && BarangM::findOne($barang_id) !== null) {
                $model= BarangM::findOne($barang_id);
                $modJualBarangDet->barang_id = $model->barang_id;
                $modJualBarangDet->qty_jual = 1;
                $rows = $this->renderPartial('_rowBarang', ['model' => $model,'modJualBarangDet'=>$modJualBarangDet, 'urutan' => $urutan]);
            } else {
                $rows = null;
            }
            echo Json::encode($rows);
            Yii::$app->end();
        }
    }
}

?>

backend/views/transaksibarang/_rowBarang.php
<?php
/**
 * Created by PhpStorm.
 * User: taufik
 * Date: 05/04/16
 * Time: 11:35
 */
use yii\helpers\Html;
use backend\models\BahanM;
use yii\helpers\ArrayHelper;

$dataBahan = ArrayHelper::map(BahanM::find()->all(), 'bahan_id', 'bahan_nama' );
?>
<tr>
    <td><?= $urutan+1; ?></td>
    <td><?= $model->barang_kode; ?>
        <?= Html::activeHiddenInput($modJualBarangDet,'['.$urutan.']barang_id'); ?></td>
    <td><?= $model->barang_nama; ?></td>
    <td><?= Html::activeTextInput($modJualBarangDet,'['.$urutan.']ukuran',['style'=>'width:100px;']); ?></td>
    <td><?= Html::activeDropDownList($modJualBarangDet,'['.$urutan.']bahan_id',$dataBahan,['prompt'=>'- Pilih Bahan - ']); ?></td>
    <td><?= Html::activeTextInput($modJualBarangDet,'['.$urutan.']harga_satuan',['style'=>'width:100px;','onChange'=>'hitungAll(this);']); ?></td>
    <td><?= Html::activeTextInput($modJualBarangDet,'['.$urutan.']qty_jual',['style'=>'width:30px;','onChange'=>'hitungAll(this);']); ?></td>
    <td><?= Html::activeTextInput($modJualBarangDet,'['.$urutan.']jumlah',['style'=>'width:100px;']); ?></td>
    <td><?= Html::activeTextarea($modJualBarangDet,'['.$urutan.']keterangan') ?></td>
    <td></td>
</tr>

backend/views/transaksibarang/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;
use yii\jui\AutoComplete;
use yii\web\JsExpression;
use backend\models\PelangganM;
use backend\models\BarangM;
use kartik\select2\Select2;
use kartik\typeahead\TypeaheadBasic;
use yii\helpers\ArrayHelper;

$this->title = 'Transaksi Order Barang';
$this->params['breadcrumbs'][] = $this->title;

//Data & Default Data
$dataPelanggan = ArrayHelper::map(PelangganM::find()->all(), 'pelanggan_id', 'pelanggan_nama' );
$dataBarang = ArrayHelper::map(BarangM::find()->all(),'barang_id','barang_nama');
$model->tgl_jual = date('d M Y');
?>

<style>
    .panjer{
        display: none;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
<!--            <h1><i class="fa fa-exchange"></i> Tambah Transaksi</h1><br>-->
            <?php $form = ActiveForm::begin(); ?>
            <div class="row">
                <div class="col-md-12">
                    <?php $model->kode_transaksi = $model->getKodeTransaksi(); ?>
                    <?= $form->field($model,'kode_transaksi')->textInput(['readonly'=>'readonly']) ?>
                </div>
                <div class="col-md-6">
                    <?php //echo $form->field($model,'pelanggan_id')->dropDownList($listPelanggan,['prompt'=>'- Pilih Pelanggan -','class'=>'form-control']); ?><!-- -->
                    <div class="form-group field-jualbarangt-pelanggan_id required">
<!--                        <label for="jualbarangt-pelanggan_id" class="control-label">Nama Client</label>-->
                        <?= $form->field($model, 'pelanggan_id')->widget(Select2::classname(), [
                            'data' => $dataPelanggan,
                            'language' => 'en',
                            'options' => ['placeholder' => 'Ketik Nama Pelanggan . . .'],
                            'pluginOptions' => [
                                'allowClear' => true
                            ],
                        ]);
                        ?>
                    </div>
                    <div class="form-group field-jualbarangt-tgl_jual required">
                        <label for="jualbarangt-tgl_jual" class="control-label">Tanggal Jual</label>
                        <?= DatePicker::widget([
                            'model' => $model,
                            'attribute' => 'tgl_jual',
                            'language' => 'en',
                            'dateFormat' => 'php:d M Y',
                            'options'=>['class'=>'form-control'],
                        ]); ?>
                    </div>
                    <div class="form-group field-jualbarangt-tgl_ambil required">
                        <label for="jualbarangt-tgl_ambil" class="control-label">Tanggal Pengambilan</label>
                        <?= DatePicker::widget([
                            'model' => $model,
                            'attribute' => 'tgl_ambil',
                            'language' => 'en',
                            'dateFormat' => 'php:d M Y',
                            'options'=>['class'=>'form-control'],
                        ]); ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <?= $form->field($model,'cara_bayar')->dropDownList(['angsur'=>'Angsur','cash'=>'Cash','nanti'=>'Nanti'],['prompt'=>'- Pilih Cara Bayar- ','onChange'=>'formPanjer(this);']); ?>
                    <div class="panjer">
                        <div class="form-group field-jualbarangt-tgl_penagihan">
                            <label for="jualbarangt-tgl_penagihan" class="control-label">Tanggal Penagihan</label>
                            <?= DatePicker::widget([
                                'model' => $model,
                                'attribute' => 'tgl_penagihan',
                                'language' => 'en',
                                'dateFormat' => 'php:d M Y',
                                'options'=>['class'=>'form-control']
                            ]); ?>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field($model,'panjer'); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field($model,'sisa'); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <fieldset>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group field-jualbarangt-barang">
                                    <?= $form->field($model, 'barang')->widget(Select2::classname(), [
                                        'data' => $dataBarang,
                                        'language' => 'en',
                                        'options' => ['placeholder' => 'Ketik Barang . . .'],
                                        'pluginOptions' => [
                                            'allowClear' => true
                                        ],
                                    ]);
                                    ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <?= Html::button('<i class="fa fa-plus"></i>',
                                    ['class'=>'btn btn-success','style'=>'margin-top:25px;','onClick'=>'tambahBarang(this);return false;']); ?>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-12">
                    <table class="table table-striped table-bordered" id="tabel-Data">
                        <thead>
                        <tr>
                            <td>No</td>
                            <td>Kode</td>
                            <td>Barang</td>
                            <td>Ukuran</td>
                            <td>Bahan</td>
                            <td>Harga Satuan</td>
                            <td>Jumlah</td>
                            <td>Total</td>
                            <td>Keterangan</td>
                            <td>Batal</td>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <div class="col-md-12">
                    <?= Html::submitButton( '<i class="fa fa-plus"></i> Tambah', ['class' =>'btn btn-success','disabled'=>$model->isNewRecord ?FALSE:TRUE]) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<script>
    function formPanjer(obj) {
        var cara_bayar = $(obj).val();
        if(cara_bayar != 'cash'){
            $('.panjer').fadeIn('slow');
        }else{
            $('.panjer').fadeOut('slow');
        }
    }

    function tambahBarang(obj) {
        var barang_id = $(obj).parents('fieldset').find('#jualbarangt-barang');
        var urutan = document.getElementById('tabel-Data').getElementsByTagName("tbody")[0].getElementsByTagName("tr").length;;
        $.ajax({
            type:'POST',
            url:'<?= Yii::$app->urlManager->createUrl('transaksibarang/tambahbarang') ?>',
            data:{barang_id:barang_id.val(),urutan:urutan},
            dataType:'json',
            success:function (result) {
                barang_id.val('');
                $('#tabel-Data > tbody').append(result);
            }
        })
    }

    function hitungAll(obj){
        var harga_satuan = $(obj).parents('tr').find('input[name*="[harga_satuan]"]').val();
        var qty_tindakan = $(obj).parents('tr').find('input[name*="[qty_jual]"]').val();

        var jumlah = harga_satuan*qty_tindakan;

        $(obj).parents('tr').find('input[name*="[jumlah]"]').val(jumlah);
    }
</script>